-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  role text DEFAULT 'user'::text,
  display_name text,
  avatar_url text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'suspended'::text])),
  last_seen_at timestamp with time zone DEFAULT now(),
  referred_by_code text,
  referred_by uuid,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_referred_by_code_fkey FOREIGN KEY (referred_by_code) REFERENCES public.invites(code),
  CONSTRAINT profiles_referred_by_fkey FOREIGN KEY (referred_by) REFERENCES auth.users(id)
);
CREATE TABLE public.invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  uses integer DEFAULT 0,
  max_uses integer DEFAULT 1,
  CONSTRAINT invites_pkey PRIMARY KEY (id),
  CONSTRAINT invites_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.power_rankings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  season text NOT NULL,
  order jsonb NOT NULL,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT power_rankings_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.power_ranking_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  season text NOT NULL,
  order jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT power_ranking_history_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user_history FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.teams (
  id integer NOT NULL,
  name text NOT NULL,
  abbrev text,
  place text,
  logo text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  primary_color text CHECK (primary_color IS NULL OR primary_color ~* '^#[0-9a-f]{6}$'::text),
  secondary_color text CHECK (secondary_color IS NULL OR secondary_color ~* '^#[0-9a-f]{6}$'::text),
  CONSTRAINT teams_pkey PRIMARY KEY (id)
);
CREATE TABLE public.playoff_series (
  id bigint NOT NULL DEFAULT nextval('playoff_series_id_seq'::regclass),
  bracket_year integer NOT NULL,
  series_letter text,
  series_title text,
  series_abbrev text,
  round_number integer,
  top_seed_team_id integer,
  top_seed_abbrev text,
  top_seed_wins integer,
  bottom_seed_team_id integer,
  bottom_seed_abbrev text,
  bottom_seed_wins integer,
  winning_team_id integer,
  losing_team_id integer,
  series_url text,
  series_logo text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  top_seed_rank integer,
  bottom_seed_rank integer,
  CONSTRAINT playoff_series_pkey PRIMARY KEY (id),
  CONSTRAINT playoff_series_bottom_seed_team_id_fkey FOREIGN KEY (bottom_seed_team_id) REFERENCES public.teams(id),
  CONSTRAINT playoff_series_losing_team_id_fkey FOREIGN KEY (losing_team_id) REFERENCES public.teams(id),
  CONSTRAINT playoff_series_top_seed_team_id_fkey FOREIGN KEY (top_seed_team_id) REFERENCES public.teams(id),
  CONSTRAINT playoff_series_winning_team_id_fkey FOREIGN KEY (winning_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.players (
  id integer NOT NULL,
  first_name text,
  last_name text,
  position text,
  shoots_catches text,
  birth_date date,
  birth_country text,
  height_in_cm integer,
  weight_in_kg integer,
  draft_year integer,
  draft_round integer,
  draft_overall_pick integer,
  draft_team_abbrev text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT players_pkey PRIMARY KEY (id)
);
CREATE TABLE public.games (
  id integer NOT NULL,
  season integer NOT NULL,
  game_type integer NOT NULL,
  date date NOT NULL,
  home_team_id integer NOT NULL,
  away_team_id integer NOT NULL,
  home_score integer,
  away_score integer,
  game_state text,
  venue text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  start_time_utc timestamp with time zone,
  last_period_type text,
  ot_periods integer,
  home_sog integer,
  away_sog integer,
  shootout_in_use boolean,
  ot_in_use boolean,
  reg_periods integer,
  star1_player_id integer,
  star2_player_id integer,
  star3_player_id integer,
  CONSTRAINT games_pkey PRIMARY KEY (id),
  CONSTRAINT games_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams(id),
  CONSTRAINT games_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_standings (
  id integer NOT NULL DEFAULT nextval('team_standings_id_seq'::regclass),
  team_id integer,
  season_id integer NOT NULL,
  game_type_id integer NOT NULL,
  as_of_date timestamp with time zone NOT NULL,
  conference_abbrev text,
  conference_home_sequence integer,
  conference_l10_sequence integer,
  conference_name text,
  conference_road_sequence integer,
  conference_sequence integer,
  division_abbrev text,
  division_home_sequence integer,
  division_l10_sequence integer,
  division_name text,
  division_road_sequence integer,
  division_sequence integer,
  games_played integer,
  wins integer,
  losses integer,
  ot_losses integer,
  ties integer,
  points integer,
  point_pctg double precision,
  win_pctg double precision,
  goal_differential integer,
  goal_differential_pctg double precision,
  goal_for integer,
  goal_against integer,
  goals_for_pctg double precision,
  home_games_played integer,
  home_goals_for integer,
  home_goals_against integer,
  home_goal_differential integer,
  home_wins integer,
  home_losses integer,
  home_ot_losses integer,
  home_points integer,
  home_regulation_wins integer,
  home_regulation_plus_ot_wins integer,
  home_ties integer,
  road_games_played integer,
  road_goals_for integer,
  road_goals_against integer,
  road_goal_differential integer,
  road_wins integer,
  road_losses integer,
  road_ot_losses integer,
  road_points integer,
  road_regulation_wins integer,
  road_regulation_plus_ot_wins integer,
  road_ties integer,
  l10_games_played integer,
  l10_goals_for integer,
  l10_goals_against integer,
  l10_goal_differential integer,
  l10_wins integer,
  l10_losses integer,
  l10_ot_losses integer,
  l10_points integer,
  l10_regulation_wins integer,
  l10_regulation_plus_ot_wins integer,
  l10_ties integer,
  league_home_sequence integer,
  league_road_sequence integer,
  league_l10_sequence integer,
  league_sequence integer,
  shootout_wins integer,
  shootout_losses integer,
  waivers_sequence integer,
  wildcard_sequence integer,
  regulation_wins integer,
  regulation_plus_ot_wins integer,
  regulation_win_pctg double precision,
  regulation_plus_ot_win_pctg double precision,
  streak_code text,
  streak_count integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_standings_pkey PRIMARY KEY (id),
  CONSTRAINT team_standings_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.game_goalie_stats (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  game_id integer NOT NULL,
  player_id integer NOT NULL,
  team_id integer NOT NULL,
  is_home boolean NOT NULL,
  starter boolean,
  decision text,
  toi text,
  shots_against integer,
  saves integer,
  goals_against integer,
  save_pctg double precision,
  even_strength_shots_against integer,
  even_strength_goals_against integer,
  power_play_shots_against integer,
  power_play_goals_against integer,
  shorthanded_shots_against integer,
  shorthanded_goals_against integer,
  pim integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT game_goalie_stats_pkey PRIMARY KEY (id),
  CONSTRAINT game_goalie_stats_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id),
  CONSTRAINT game_goalie_stats_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT game_goalie_stats_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.game_plays (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  game_id integer NOT NULL,
  event_id integer NOT NULL,
  sort_order integer,
  type_code integer,
  type_desc_key text,
  period integer,
  period_type text,
  time_in_period text,
  time_remaining text,
  situation_code text,
  x_coord double precision,
  y_coord double precision,
  zone_code text,
  shot_type text,
  event_owner_team_id integer,
  shooting_player_id integer,
  goalie_in_net_id integer,
  scoring_player_id integer,
  blocking_player_id integer,
  hitting_player_id integer,
  hittee_player_id integer,
  away_score integer,
  home_score integer,
  away_sog integer,
  home_sog integer,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT game_plays_pkey PRIMARY KEY (id),
  CONSTRAINT game_plays_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id)
);
CREATE TABLE public.game_shifts (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  game_id integer NOT NULL,
  player_id integer NOT NULL,
  team_id integer NOT NULL,
  period integer,
  shift_number integer,
  start_time text,
  end_time text,
  duration text,
  type_code integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT game_shifts_pkey PRIMARY KEY (id),
  CONSTRAINT game_shifts_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id),
  CONSTRAINT game_shifts_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT game_shifts_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.game_skater_stats (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  game_id integer NOT NULL,
  player_id integer NOT NULL,
  team_id integer NOT NULL,
  is_home boolean NOT NULL,
  position text,
  toi text,
  goals integer,
  assists integer,
  points integer,
  plus_minus integer,
  pim integer,
  hits integer,
  sog integer,
  blocked_shots integer,
  power_play_goals integer,
  faceoff_winning_pctg double precision,
  giveaways integer,
  takeaways integer,
  shifts integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT game_skater_stats_pkey PRIMARY KEY (id),
  CONSTRAINT game_skater_stats_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id),
  CONSTRAINT game_skater_stats_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT game_skater_stats_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.game_team_stats (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  game_id integer NOT NULL,
  team_id integer NOT NULL,
  is_home boolean NOT NULL,
  pp_pctg double precision,
  pk_pctg double precision,
  faceoff_winning_pctg double precision,
  hits integer,
  blocked_shots integer,
  pim integer,
  sog integer,
  created_at timestamp with time zone DEFAULT now(),
  giveaways integer,
  takeaways integer,
  CONSTRAINT game_team_stats_pkey PRIMARY KEY (id),
  CONSTRAINT game_team_stats_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id),
  CONSTRAINT game_team_stats_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.game_advanced_stats (
  game_id bigint NOT NULL,
  team_id bigint NOT NULL,
  season bigint,
  date date,
  cf real,
  ca real,
  xgf real,
  xga real,
  hdcf real,
  hdca real,
  cf_pct real,
  xgf_pct real,
  hdcf_pct real,
  ff real,
  fa real,
  cf_5v5 real,
  ca_5v5 real,
  xgf_5v5 real,
  xga_5v5 real,
  hdcf_5v5 real,
  hdca_5v5 real,
  cf_pct_5v5 real,
  xgf_pct_5v5 real,
  hdcf_pct_5v5 real,
  sh_pct real,
  sv_pct real,
  sh_pct_5v5 real,
  sv_pct_5v5 real,
  pdo real,
  pdo_5v5 real,
  hdgf integer,
  hdga integer,
  hdsh_pct real,
  hdsv_pct real,
  mdcf real,
  mdca real,
  ldcf real,
  ldca real,
  xgf_pp real,
  xga_pk real,
  cf_pp real,
  ca_pk real,
  scf real,
  sca real,
  scf_pct real,
  CONSTRAINT game_advanced_stats_pkey PRIMARY KEY (game_id, team_id)
);
CREATE TABLE public.game_goalie_advanced_stats (
  game_id bigint NOT NULL,
  player_id bigint NOT NULL,
  team_id bigint,
  season bigint,
  date date,
  shots_faced integer,
  xga real,
  goals_against integer,
  gsax real,
  xga_5v5 real,
  gsax_5v5 real,
  xga_pk real,
  goals_against_pk integer,
  gsax_pk real,
  ld_shots integer,
  ld_goals_against integer,
  md_shots integer,
  md_goals_against integer,
  hd_shots integer,
  hd_goals_against integer,
  save_pct_above_exp real,
  flurry_adjust_xga real,
  rebounds_given integer,
  freeze_pct real,
  CONSTRAINT game_goalie_advanced_stats_pkey PRIMARY KEY (game_id, player_id)
);
CREATE TABLE public.game_skater_advanced_stats (
  game_id bigint NOT NULL,
  player_id bigint NOT NULL,
  team_id bigint,
  season bigint,
  date date,
  icf integer,
  iff integer,
  ixg real,
  cf_pct real,
  ff_pct real,
  sf_pct real,
  gf_pct real,
  xgf_pct real,
  pdo real,
  cf_pct_rel real,
  xgf_pct_rel real,
  ozs_pct real,
  toi_seconds integer,
  CONSTRAINT game_skater_advanced_stats_pkey PRIMARY KEY (game_id, player_id)
);
